### ISSUE TITLE
Missing double qoutes

### ISSUE THREAD

**Issue by waleyeldeen** [Omar-Sayed95/snitch-sniffer#5]
### Error:
At line 1 in [snitch-sniffer.py](https://github.com/Omar-Sayed95/snitch-sniffer/blob/master/snitch-sniffer.py):
It is: `print("Hello world!`)
### Solution:
`print("Hello world!")`

**Comment by Omar-Sayed95** [comment]
Received with thanks @weko10 .

**Comment by Mostafa2291** [comment]
yes
