### ISSUE TITLE
a missing quotation in the code 

### ISSUE THREAD

**Issue by Mostafa2291** [Omar-Sayed95/snitch-sniffer#6]
in the code [snitch-sniffer](https://github.com/Omar-Sayed95/snitch-sniffer/blob/master/snitch-sniffer.py), there is a line called 
'print ("Hello world!)'

however it is incorrect, and it should be corrected to: 
'print("Hello world!")

**Comment by Omar-Sayed95** [comment]
I need more clarification, what is incorrect specifically?

**Comment by Mostafa2291** [comment]
line 1; there is no end quotation for the print

**Comment by Mostafa2291** [comment]
hello

**Comment by 360Ahmad** [comment]
Washable code!!!

**Comment by waleyeldeen** [comment]
test
